### ISSUE TITLE
Table vs. list readability?

### ISSUE THREAD

**Issue by Martin-Pitt** [notoriousb1t/awesome-css-variables#1]
I find the table layout hard to read.

Think the author's could be easily inlined links in the description if we needed to have them. (Wherever description mentions the authors name already should be turned into a link for example)

Contrast this table layout vs. the list at: https://github.com/awesome-css-group/awesome-css

The "[Think outside the database](https://twitter.com/steveschoger/status/997125312411570176)" applies here.

Granted, markdown does not leave much room, but rewriting copy to be more succinct would help a lot.

For example going from:

|Resource|Author|Description|
|-|-|-|
|[A Strategy Guide To CSS Custom Properties](https://www.smashingmagazine.com/2018/05/css-custom-properties-strategy-guide/ )|[Michael Riethmuller](https://www.smashingmagazine.com/author/michaelriethmuller/)|This article outlines the basics of using CSS Variables by comparing them to variables found in pre-processors such as Sass.|
|[CSS Custom Properties and Theming](https://css-tricks.com/css-custom-properties-theming/ )|[Chris Coyier](https://twitter.com/chriscoyier)|This post shows how CSS Variables can be used to dynamically theme websites.  This is a common problem when "white labeling" digital content.|
|[Using CSS custom properties (variables)](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables)|N/A|This is the definitive guide for getting started with CSS Variables. Like most of their other content, MDN continues to be the best place to learn in depth how web technology works short of reading the actual specifications.|
|[Learn CSS Variables for free](https://scrimba.com/playlist/ppYrcJ)|[Per Harald Borgen](https://twitter.com/perborgen)|This free video series takes the viewer through the basics of CSS Variables, how to use them in theming, and how to change them through JavaScript.| 
|[Individualizing CSS Properties with CSS Variables](https://danielcwilson.com/blog/2017/04/individualized-properties/)|[@dancwilson](https://twitter.com/dancwilson)|This article is an exploration of using CSS Variables in different CSS Properties such as animation-play-state, transforms, and in color channels. As usual, a great and thoughtful read by Dan Wilson.| 

to:

* [A Strategy Guide To CSS Custom Properties](https://www.smashingmagazine.com/2018/05/css-custom-properties-strategy-guide/) – by comparing them to variables in pre-processors, such as Sass – by [Michael Riethmuller](https://www.smashingmagazine.com/author/michaelriethmuller/)
* [CSS Custom Properties and Theming](https://css-tricks.com/css-custom-properties-theming/ ) – and how they can be used to dynamically theme websites – by [Chris Coyier](https://twitter.com/chriscoyier)
* [Using CSS custom properties (variables)](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) – is a definitive guide for getting started at MDN
* [Learn CSS Variables for free](https://scrimba.com/playlist/ppYrcJ) – a video course by [Per Harald Borgen](https://twitter.com/perborgen) that takes you through the basics, theming and to JavaScript
* [Individualizing CSS Properties with CSS Variables](https://danielcwilson.com/blog/2017/04/individualized-properties/) – in different properties such as `animation-play-state`, `transform`s, and color channels. Great and thoughtful read by [Dan Wilson](http://danielcwilson.com/about/). 

First I rewrote the copy to read fluently. Then I took the first link and made it stand out prominently, by using the pause from the em-dash. Making it easier to scan horizontally and contrast vertically.

Ideally, descriptions should be small enough to fit on a single line on desktop view, as the README.md isn't as compact as the issues view here. Also a fun challenge for rewriting terse! :)

Does the criticism and suggestion make sense otherwise? This is your curated list after all – I don't want to impose. If you feel like you prefer large descriptions then so be it.

**Comment by shshaw** [comment]
I think I pushed @notoriousb1t into the table layout 😁 
Originally there were large headings for each and the tables were a good way to create a more space efficient layout. I'm not opposed to the list layout, though I'd recommend making the titles bold to help them stand out in a sea of text.

* [**A Strategy Guide To CSS Custom Properties**]() – Comparing CSS variables to pre-processor variables, such as Sass – by [Michael Riethmuller]()
* [**CSS Custom Properties and Theming**]() – How CSS variables can be used to dynamically theme websites – by [Chris Coyier]()

**Comment by notoriousb1t** [comment]
I’m good with both of your suggestions. I’m going to be a little out of pocket until early next week, so if either of you want to make the changes, I would welcome a PR for this even if it is for specific sections 😀

Otherwise I will probably be able to get to it in the evening next week.

**Comment by notoriousb1t** [comment]
I updated the format back to listview. How does that look guys?  I haven't gone through to reduce the descriptions just yet, but I think this will at least make it more readable.

**Comment by Martin-Pitt** [comment]
That looks great so far on my mobile, will need to check on my laptop as well
