### ISSUE TITLE
Hybrid Positioning with CSS Variables & max()

### ISSUE THREAD

**Issue by Martin-Pitt** [notoriousb1t/awesome-css-variables#4]
This is a really cool article by @LeaVerou on hybrid positioning:
https://lea.verou.me/2020/06/hybrid-positioning-with-css-variables-and-max/

Uses the CSS variables scrollTop technique together with the well supported max(), min() functions.

It's quite interesting, because position: sticky has a problem. Sticky is good if your element is already static or relative — but if it's absolute then you don't have a good alternative. This technique works around it with a different approach to emulating the sticky-like behaviour from the ground up, but mostly relying on modern CSS to reach near-perfect separation of concerns.

Let's see, how about this…

* **[Hybrid Positioning with CSS Variables and max()](https://lea.verou.me/2020/06/hybrid-positioning-with-css-variables-and-max/)** – Lea shares a useful technique when you are using an absolute position element but still want a sticky behaviour – by [Lea Verou](https://lea.verou.me/about/)

**Comment by notoriousb1t** [comment]
I added this. Thanks for the contribution as always!
